language: bash

services:
  - docker

script:
  - docker pull alpine:latest
  - docker run --rm alpine:latest echo "Hello from inside Alpine!" 
  - docker run --rm alpine:latest sh -c "cat /etc/os-release && uname -a"
  - docker run --rm alpine:latest sh -c "apk add --no-cache figlet > /dev/null && figlet 'Alpine!'"
